---
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false